package gaps

import (
	"fmt"
	"io"
	"sort"
	"strings"
)

// Markdown writes a deterministic markdown rendering of the static
// registry to w. The output is sorted by gap ID so reruns of
// `mockta gaps export` produce byte-identical files; the CI drift
// check depends on this property.
func Markdown(w io.Writer, entries []Gap) error {
	out := make([]Gap, len(entries))
	copy(out, entries)
	sort.Slice(out, func(i, j int) bool { return out[i].ID < out[j].ID })

	sections := []string{
		"# mockta gap list",
		"",
		"This page is auto-generated by `mockta gaps export`. Do not",
		"edit by hand — changes will be overwritten on the next build.",
		"",
		"Each row is a slice of the Okta Management API that mockta",
		"does not implement. Requests that hit these surfaces return",
		"501 (or 400 for invalid filter expressions) with the listed",
		"`errorCode` in the response body and an `X-Mockta-Gap` header",
		"on the response. File a feature request referencing the gap",
		"ID to vote it onto the roadmap.",
		"",
		"| ID | Endpoint | Resource | Status | Notes |",
		"|----|----------|----------|--------|-------|",
	}
	if _, err := fmt.Fprintln(w, strings.Join(sections, "\n")); err != nil {
		return fmt.Errorf("write header: %w", err)
	}

	for _, g := range out {
		notes := strings.ReplaceAll(g.Notes, "|", `\|`)
		notes = strings.ReplaceAll(notes, "\n", " ")
		if _, err := fmt.Fprintf(w,
			"| `%s` | `%s` | %s | %s | %s |\n",
			g.ID, g.Endpoint, g.Resource, g.Status, notes,
		); err != nil {
			return fmt.Errorf("write row %s: %w", g.ID, err)
		}
	}
	return nil
}
